### ISSUE TITLE
players can re-sleep immediately uninterrupted

### ISSUE THREAD

**Issue by leasoncre** [JoelGodOfwar/SinglePlayerSleep#10]
Hello, having some weird issues while testing this out: [ Paper 1.15.2 | Win10HostVM | Java8u241 | SPS 1.13_2.13.34 ]
1. can't use multiple formatting values (Trying to use BOLD and YELLOW for sleepmsgcolor) not sure how to state this in config correctly. 
1b. adding a character (space or anything) adds those characters before & after the player name as well as after the cancel text (this is actually wierd to me) https://i.gyazo.com/08df31a4c940207a6ca29e01d5a6e4b1.png
2. if a player sleeps. and someone cancels it, they can just jump back in bed uninterrupted while anyone trying to cancel it again is told there is nothing to cancel
If this is because i'm resetting (day/night) manullay before a timer runs out, the timer should be reset immediately upon action taken.
And/or if the player tried to sleep again, within x time it should tell the player 'sleep was canceled by <player> when they click the bed (if broadcast is disabled) and say something like sleeping disabled for x seconds, please try again later.

[config - Copy.txt](https://github.com/JoelGodOfwar/SinglePlayerSleep/files/4232932/config.-.Copy.txt)

PS. the discord link(s) on your plugin's page's are invalid ><

**Comment by JoelGodOfwar** [comment]
1. I don't know why but the formatting only works if it is after the color, YELLOWBOLD works while BOLDYELLOW does not. Something about the way mojang handles the color codes.
1b. I don't see any extra characters in your config, Where were they added?
2. In your config you have sleeplimit set to 0, this means that they can attempt to sleep again right after trying, if you set it to say 60, then they can not try to sleep again until 60 seconds has passed.
I have tested this on my test server, If a player sleeps, and someone cancels, and then the player sleeps again, with sleeplimit set to 0, the broadcast goes out again, and if you click cancel, it will tell you there is nothing to cancel, but the time will not change. If the time is changing on your server, please enable debug and send me a log of players trying to cheat the sleep system.

**Comment by JoelGodOfwar** [comment]
Also the discord links have been fixed, thank you for letting me know they were expired.

**Comment by leasoncre** [comment]
1. I didn't see syntaxing instructions for multiple values [YELLOWBOLD] so i had tried with a space, comma, and an underscore before sending this. | Oh yeah, Derp, i forgot that the colors reset the other variables.
2. oh! ok, i must have miss-understood when i changed that. but yeah, with that set to 0 it is changeing the time shortly there after (like roughly 10sec after the first sleep attempt)
--trying debug: log [2020-02-21-3.log](https://github.com/JoelGodOfwar/SinglePlayerSleep/files/4236787/2020-02-21-3.log)
3. oh, is this plugin sending 'Respawn point Set` messages? sometimes it's sent twice.
https://i.gyazo.com/76a32754db518dd142a53270ebd506d1.png
