### ISSUE TITLE
Unnecessary version updates?

### ISSUE THREAD

**Issue by spiritedsnowcat** [JoelGodOfwar/SinglePlayerSleep#11]
Hi,

Is there any particular reason why there are empty commits to just update the version? I don't know if it's to push your mod to the top of the "recently updated" list every once in a while, but it's causing my server to output "new version available" messages to all players. An explanation would be nice.

Thanks.

**Comment by JoelGodOfwar** [comment]
Not sure what you're asking, I update the version.txt file when I release a new version, but I have no idea how that would affect your server? Maybe you can explain on my discord server? https://discord.gg/Bh5YDRC

**Comment by spiritedsnowcat** [comment]
I guess what I'm asking is, why are the commits for the new version only updating version.txt? For example, the latest version: https://github.com/JoelGodOfwar/SinglePlayerSleep/commit/fe9fad3293ff4af312c89c22558a31113cb02091

**Comment by JoelGodOfwar** [comment]
It's part of my version checking system. I haven't updated the source yet, but will after I clean up the code a little.

**Comment by spiritedsnowcat** [comment]
Hm, ok. Is there anywhere I can see what the latest version is? Like a change log? Thanks.

**Comment by JoelGodOfwar** [comment]
https://www.spigotmc.org/resources/single-player-sleep.68139/updates has change logs.
https://www.spigotmc.org/resources/single-player-sleep.68139/history shows the current version and a download link.

**Comment by spiritedsnowcat** [comment]
Ah, ok. Thanks.
