### ISSUE TITLE
Feature: Prefix

### ISSUE THREAD

**Issue by winnipeg21** [JoelGodOfwar/SinglePlayerSleep#12]
Allow for the ability to change prefix with color codes, I like to keep the plugins under the same message format and this would make it a lot better!

**Comment by JoelGodOfwar** [comment]
can you give me an example of what you're talking about? https://discord.gg/Bh5YDRC

**Comment by winnipeg21** [comment]
Like when you do /sps reload it says "SinglePlayerSleep SinglePlayerSleep has been reloaded." (with the first singleplayersleep being the prefix). So I could change it to be like "[SPS] Plugin has been reloaded!". with all command outputs having the prefix and define that in the lang file

**Comment by JoelGodOfwar** [comment]
You can get rid of the double SinglePlayerSleep by modifying the lang file en_US.yml, and removing the leading SinglePlayerSleep in the file. Somehow that made it past my beta testing.
But I need the SinglePlayerSleep part to let me review logs for issues, So I probably will not add a custom prefix. I may offer a config to shorten it to SPSv?.??_?.??.??

**Comment by winnipeg21** [comment]
I mean sure add a shorten option.. Or allow custom prefixes and make a debug option that dumps everything to a seperate folder kinda like some other plugins. The debug would just display your plugin issues and excludes the other plugin garbage that builds up in console.

**Comment by JoelGodOfwar** [comment]
No longer needed as this is now an option in the config.yml.
