### ISSUE TITLE
Inconsistency between ability to click left and right hand brackets of the [Cancel] sleep chat component.

### ISSUE THREAD

**Issue by WiIIiam278** [JoelGodOfwar/SinglePlayerSleep#13]
### What behaviour is expected:
The left and right hand brackets of the [CANCEL] button chat component that appears when someone enters a bed would either both be clickable, or not clickable.

### What behaviour is observed:
The left and right hand brackets of the [CANCEL] button chat component that appears when someone enters a bed are inconsistent in the ability to click them. The left hand bracket is impossible to click, whereas the right hand bracket is. This is presumably caused by the right hand bracket being appended as a text component with no action, but the game assigns it the action of the previous chat component anyway.

### Steps/models to reproduce:
Have someone sleep in a bed
Hover mouse over the cancel button in chat, observe as the left bracket is not clickable while the right bracket is clickable.

### Plugin list:
CoreProtect, dynmap, Dynmap-GriefPrevention, LuckPerms, MobHeads, Plan, PvPToggle, QuickShop, SecuredNetwork, SinglePlayerSleep, Vault, XConomy and 2 proprietary plugins.

### Bukkit/Spigot server version or Paper build number:
Waterfall version 1.16-R0.4-SNAPSHOT:6496349:370
PaperMC version git-Paper-1daafe455

**Comment by JoelGodOfwar** [comment]
This was a simple error in placement of the ] and testing a dev version to correct it.

**Comment by JoelGodOfwar** [comment]
This issue is resolved in 1.13_2.13.44.D1 available in #dev-build of singleplayersleep on my discord server https://discord.gg/PXN4bzT
