### ISSUE TITLE
Plugin needs update.

### ISSUE THREAD

**Issue by NewgroundGaming** [JoelGodOfwar/SinglePlayerSleep#2]
This plugin needs updating to 1.10. I need a way to get one player sleep in 1.10 survival.

**Comment by JoelGodOfwar** [comment]
Updated to 1.10, If Spigot would stop changing minor names in the spigot-x.xx.jar file, this wouldn't have even needed an update to work in 1.10.

**Comment by NewgroundGaming** [comment]
The command block one man sleep for 1.9 doesn't work in 1.10 for whatever reason. Thank you for updating. Can I have a download link for the jar?

**Comment by JoelGodOfwar** [comment]
http://dev.bukkit.org/bukkit-plugins/singleplayersleep/
https://www.spigotmc.org/resources/single-player-sleep.20173/
https://github.com/JoelGodOfwar/SinglePlayerSleep/raw/master/1.10-jar/SinglePlayerSleep.jar
