### ISSUE TITLE
[Future]

### ISSUE THREAD

**Issue by ErythroCraft** [JoelGodOfwar/SinglePlayerSleep#24]
Hello

I am using your plugin on my server.

Now I installed the plugin "SurvivalPlus - Reloaded"
Survival plus is an plugin for refreshing players energie, while sleeping.
The problem is that either only one or all of them can go to bed. However, in Survival Plus, the player consumes energy throughout the day.

Can you give an update to sleep always?

1.
```
example option:
##
# This option means, player can always sleep.
# With this option, the time persists.
##
alwaysSleep : true/false

example permissions:
# Allow player sleeping every time.
singleplayersleep.alwayssleep 
```

2.
```
example option:
##
# This option means, player can sleep only in day time.
# Combinations are accepted. Time persists.
##
SleepTime: [ day, night, noon, midnight ]

example permissions:
# Allow player sleeping every time.
singleplayersleep.sleep.*
singleplayersleep.sleep.day
singleplayersleep.sleep.night
singleplayersleep.sleep.noon
singleplayersleep.sleep.midnight
```

**I would go for the second option because it's more custom.**

**Comment by JoelGodOfwar** [comment]
Please join my discord server, and explain this a little more. What is my plugin not doing that you think it should do? Or what is the other plugin not doing because of my plugin changing the time? https://discord.gg/PXN4bzT

**Comment by ErythroCraft** [comment]
closed without content
