### ISSUE TITLE
Needs to be updated for 1.12.1

### ISSUE THREAD

**Issue by cinister** [JoelGodOfwar/SinglePlayerSleep#5]
The plugin doesn't work with 1.12, I get this error whenever someone sleeps: https://hastebin.com/agebejomub

**Comment by coldcode69** [comment]
I needed it updated so I compiled a new version for 1.12, you can download it here: https://github.com/coldcode69/SinglePlayerSleep/raw/master/SinglePlayerSleep.jar

Of course, you do so at your own risk. 

I don't use the commands so I haven't tested that, but sleeping via a bed, and the cancel functionality both work without error. :)

**Comment by JoelGodOfwar** [comment]
The plugin has been updated for 1.12.x,, 1.13, and 1.13.2.
Thank you coldcode69, I like some of the features you added, and will implement them in future versions.
