### ISSUE TITLE
cancelbroadcast config not working

### ISSUE THREAD

**Issue by Chr0n4s** [JoelGodOfwar/SinglePlayerSleep#6]
I set "cancelbroadcast: false" but it still keeps sending it to chat.

**Comment by JoelGodOfwar** [comment]
What version are you using, both MC and of the plugin?
I see where the mistake is in the code, just need to know which version needs the update.

**Comment by Chr0n4s** [comment]
MC: 1.14.4
plugin: 2.13.21

**Comment by JoelGodOfwar** [comment]
update will be on spigotmc.com within an hour.

**Comment by JoelGodOfwar** [comment]
fixed in 2.13.23
